### Traer todas las tareas
GET http://localhost:3000/api/tasks

### Traer una tarea específica
GET http://localhost:3000/api/tasks/68b73e71a25accccf9c58b33

### Crear una nueva tarea
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "Nueva tarea 3",
  "description": "Descripción de la tarea 3",
  "completed": false
}

### Actualizar una tarea
PUT http://localhost:3000/api/tasks/68b7431a07c1716c0e59b76d
Content-Type: application/json

{
  "title": "Nueva tarea 3 actualizada",
  "description": "Descripción de la tarea 3 actualizada",
  "completed": true
}

### Eliminar una tarea
DELETE http://localhost:3000/api/tasks/68b73e71a25accccf9c58b33